import { Store, Deal, RetailerCategory, StoreLocation, StoreLoyaltyProgram, CategoryBalanceMetric, RetailerDiscoveryHealth } from '../src/types';

export const comprehensiveStores: Store[] = [
  // 1. GROCERY
  {
    id: 'store-kroger',
    name: 'Kroger',
    slug: 'kroger',
    domain: 'kroger.com',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'America’s largest supermarket chain with fresh produce, meat, bakery, and digital 5x fuel point savings.',
    cashbackRate: 1.5,
    allowsStacking: true,
    couponCount: 24,
    dealCount: 142,
    popularDiscountText: '$1.89/lb Chicken + 5x Fuel Points',
    verifiedScore: 98,
    loyaltyProgramName: 'Kroger Plus Card',
    loyaltyProgramPerk: 'Digital Coupons & $1/gal Fuel Points',
    hasWeeklyAd: true,
    weeklyAdCount: 45,
    digitalCouponsCount: 88,
    rewardsCount: 12,
    inStoreLocationsCount: 2750
  },
  {
    id: 'store-aldi',
    name: 'ALDI',
    slug: 'aldi',
    domain: 'aldi.us',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'No-frills grocery retailer offering everyday low prices on quality private label foods and weekly ALDI Finds.',
    cashbackRate: 0,
    allowsStacking: false,
    couponCount: 8,
    dealCount: 65,
    popularDiscountText: '$1.49 Fresh Strawberries & Produce',
    verifiedScore: 99,
    loyaltyProgramName: 'No Membership Needed',
    loyaltyProgramPerk: 'Everyday direct wholesale markdowns',
    hasWeeklyAd: true,
    weeklyAdCount: 32,
    digitalCouponsCount: 0,
    rewardsCount: 0,
    inStoreLocationsCount: 2300
  },
  {
    id: 'store-costco',
    name: 'Costco Wholesale',
    slug: 'costco',
    domain: 'costco.com',
    logo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'Wholesale warehouse club providing bulk groceries, Kirkland Signature items, electronics, and discount fuel.',
    cashbackRate: 2.0,
    allowsStacking: false,
    couponCount: 18,
    dealCount: 120,
    popularDiscountText: '$3.50 Off Kirkland Paper Towels',
    verifiedScore: 99,
    loyaltyProgramName: 'Costco Gold Star Membership',
    loyaltyProgramPerk: 'Warehouse instant savings & 2% Executive Reward',
    hasWeeklyAd: true,
    weeklyAdCount: 50,
    digitalCouponsCount: 0,
    rewardsCount: 6,
    inStoreLocationsCount: 600
  },
  {
    id: 'store-samsclub',
    name: "Sam's Club",
    slug: 'sams-club',
    domain: 'samsclub.com',
    logo: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'Bulk wholesale club with Member’s Mark pantry staples, Scan & Go mobile checkout, and Instant Savings.',
    cashbackRate: 3.0,
    allowsStacking: false,
    couponCount: 22,
    dealCount: 110,
    popularDiscountText: 'Instant Savings Book + 50% Off First Year Club Pass',
    verifiedScore: 97,
    loyaltyProgramName: "Sam's Club Membership",
    loyaltyProgramPerk: 'Scan & Go Instant Savings + Sam’s Cash',
    hasWeeklyAd: true,
    weeklyAdCount: 40,
    digitalCouponsCount: 15,
    rewardsCount: 8,
    inStoreLocationsCount: 600
  },
  {
    id: 'store-meijer',
    name: 'Meijer',
    slug: 'meijer',
    domain: 'meijer.com',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'Midwestern supercenter pioneer combining full grocery supermarket with department store savings and mPerks.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 30,
    dealCount: 95,
    popularDiscountText: 'mPerks Buy 5 Save $5 & 10 for $10 with 11th Free',
    verifiedScore: 98,
    loyaltyProgramName: 'Meijer mPerks',
    loyaltyProgramPerk: 'Personalized reward points & stackable manufacturer digital coupons',
    hasWeeklyAd: true,
    weeklyAdCount: 38,
    digitalCouponsCount: 75,
    rewardsCount: 14,
    inStoreLocationsCount: 260
  },
  {
    id: 'store-hyvee',
    name: 'Hy-Vee',
    slug: 'hy-vee',
    domain: 'hy-vee.com',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'Employee-owned Midwest supermarket chain known for friendly service, fuel saver discounts, and bakery specials.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 19,
    dealCount: 82,
    popularDiscountText: 'Hy-Vee Fuel Saver + Red Hot Weekend Specials',
    verifiedScore: 96,
    loyaltyProgramName: 'Hy-Vee Fuel Saver + Perks',
    loyaltyProgramPerk: '$0.20 to $1.00/gal gas savings per qualifying item',
    hasWeeklyAd: true,
    weeklyAdCount: 28,
    digitalCouponsCount: 50,
    rewardsCount: 10,
    inStoreLocationsCount: 285
  },
  {
    id: 'store-publix',
    name: 'Publix',
    slug: 'publix',
    domain: 'publix.com',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'Premier Southeastern supermarket chain famed for famous weekly BOGO deals and Club Publix perks.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 26,
    dealCount: 115,
    popularDiscountText: 'Weekly BOGO Free Extravaganza',
    verifiedScore: 99,
    loyaltyProgramName: 'Club Publix',
    loyaltyProgramPerk: 'Weekly BOGO preview + $5 birthday perk',
    hasWeeklyAd: true,
    weeklyAdCount: 42,
    digitalCouponsCount: 65,
    rewardsCount: 8,
    inStoreLocationsCount: 1350
  },
  {
    id: 'store-traderjoes',
    name: "Trader Joe's",
    slug: 'trader-joes',
    domain: 'traderjoes.com',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GROCERY',
    description: 'Neighborhood grocery oasis featuring inventive private-label foods, snacks, and seasonal Fearless Flyer staples.',
    cashbackRate: 0,
    allowsStacking: false,
    couponCount: 4,
    dealCount: 40,
    popularDiscountText: 'Fearless Flyer Everyday Low Price Guarantee',
    verifiedScore: 98,
    loyaltyProgramName: 'Fearless Flyer Direct',
    loyaltyProgramPerk: 'No card or coupon needed—flat direct price',
    hasWeeklyAd: true,
    weeklyAdCount: 15,
    digitalCouponsCount: 0,
    rewardsCount: 0,
    inStoreLocationsCount: 560
  },

  // 2. PHARMACY / HEALTH
  {
    id: 'store-cvs',
    name: 'CVS Pharmacy',
    slug: 'cvs',
    domain: 'cvs.com',
    logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Health & Pharmacy',
    retailerCategory: 'PHARMACY / HEALTH',
    description: 'America’s leading retail pharmacy providing prescriptions, ExtraCare rewards, ExtraBucks, and health wellness essentials.',
    cashbackRate: 4.0,
    allowsStacking: true,
    couponCount: 35,
    dealCount: 180,
    popularDiscountText: '$5 ExtraBucks + BOGO Free Vitamins',
    verifiedScore: 99,
    loyaltyProgramName: 'CVS ExtraCare',
    loyaltyProgramPerk: '2% back in ExtraBucks + send-to-card manufacturer coupon stacking',
    hasWeeklyAd: true,
    weeklyAdCount: 65,
    digitalCouponsCount: 120,
    rewardsCount: 25,
    inStoreLocationsCount: 9600
  },
  {
    id: 'store-walgreens',
    name: 'Walgreens',
    slug: 'walgreens',
    domain: 'walgreens.com',
    logo: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Health & Pharmacy',
    retailerCategory: 'PHARMACY / HEALTH',
    description: 'Trusted neighborhood pharmacy offering photo printing, weekly circular deals, and myWalgreens cash rewards.',
    cashbackRate: 3.5,
    allowsStacking: true,
    couponCount: 32,
    dealCount: 165,
    popularDiscountText: 'myWalgreens $1.25 Clip Paper Towels + 1% to 5% Cash',
    verifiedScore: 98,
    loyaltyProgramName: 'myWalgreens',
    loyaltyProgramPerk: 'Unlock sale prices, 1-5% Walgreens cash, and fast 30-min pickup',
    hasWeeklyAd: true,
    weeklyAdCount: 55,
    digitalCouponsCount: 110,
    rewardsCount: 20,
    inStoreLocationsCount: 8900
  },
  {
    id: 'store-riteaid',
    name: 'Rite Aid',
    slug: 'rite-aid',
    domain: 'riteaid.com',
    logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Health & Pharmacy',
    retailerCategory: 'PHARMACY / HEALTH',
    description: 'Full-service pharmacy and wellness destination with Rite Aid Rewards and digital pharmacy refills.',
    cashbackRate: 2.0,
    allowsStacking: true,
    couponCount: 15,
    dealCount: 75,
    popularDiscountText: 'Rite Aid Rewards Bonus Points & Weekly Ad',
    verifiedScore: 95,
    loyaltyProgramName: 'Rite Aid Rewards',
    loyaltyProgramPerk: 'Earn points convert to Rite Aid cash for prescription copays and store items',
    hasWeeklyAd: true,
    weeklyAdCount: 25,
    digitalCouponsCount: 40,
    rewardsCount: 10,
    inStoreLocationsCount: 1700
  },

  // 3. GENERAL RETAIL
  {
    id: 'store-walmart',
    name: 'Walmart',
    slug: 'walmart',
    domain: 'walmart.com',
    logo: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'General Merchandise',
    retailerCategory: 'GENERAL RETAIL',
    description: 'Everyday Low Prices on groceries, electronics, home goods, apparel, auto service, and pharmacy.',
    cashbackRate: 3.0,
    allowsStacking: false,
    couponCount: 45,
    dealCount: 320,
    popularDiscountText: 'Rollbacks up to 40% Off + Walmart Cash Rebates',
    verifiedScore: 99,
    loyaltyProgramName: 'Walmart+ & Walmart Cash',
    loyaltyProgramPerk: 'Manufacturer cashback direct to bank/account + free grocery delivery',
    hasWeeklyAd: true,
    weeklyAdCount: 60,
    digitalCouponsCount: 85,
    rewardsCount: 18,
    inStoreLocationsCount: 4700
  },
  {
    id: 'store-target',
    name: 'Target',
    slug: 'target',
    domain: 'target.com',
    logo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'General Merchandise',
    retailerCategory: 'GENERAL RETAIL',
    description: 'Trendy essentials, groceries, apparel, and home decor with automatic Target Circle savings.',
    cashbackRate: 2.0,
    allowsStacking: true,
    couponCount: 38,
    dealCount: 260,
    popularDiscountText: 'Target Circle: Spend $50 Get $15 Gift Card + 5% RedCard',
    verifiedScore: 99,
    loyaltyProgramName: 'Target Circle',
    loyaltyProgramPerk: 'Automatic deals applied at checkout + 5% with Circle Card',
    hasWeeklyAd: true,
    weeklyAdCount: 52,
    digitalCouponsCount: 95,
    rewardsCount: 15,
    inStoreLocationsCount: 1950
  },
  {
    id: 'store-dollargeneral',
    name: 'Dollar General',
    slug: 'dollar-general',
    domain: 'dollargeneral.com',
    logo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Household & Cleaning',
    retailerCategory: 'GENERAL RETAIL',
    description: 'Convenient neighborhood discount store with DG Digital Coupons, $5 off $25 Saturday events, and brand-name pantry staples.',
    cashbackRate: 1.5,
    allowsStacking: true,
    couponCount: 28,
    dealCount: 140,
    popularDiscountText: '$5 OFF $25 Saturday Coupon + Stacked Manufacturer Clips',
    verifiedScore: 98,
    loyaltyProgramName: 'DG Digital Coupons',
    loyaltyProgramPerk: 'Exclusive $5 off $25 Saturday coupon + in-app coupon clipping',
    hasWeeklyAd: true,
    weeklyAdCount: 35,
    digitalCouponsCount: 90,
    rewardsCount: 12,
    inStoreLocationsCount: 19000
  },
  {
    id: 'store-dollartree',
    name: 'Dollar Tree',
    slug: 'dollar-tree',
    domain: 'dollartree.com',
    logo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Household & Cleaning',
    retailerCategory: 'GENERAL RETAIL',
    description: 'Extreme value retailer offering $1.25 items across household cleaning, party supplies, snacks, and seasonal items.',
    cashbackRate: 1.0,
    allowsStacking: false,
    couponCount: 10,
    dealCount: 60,
    popularDiscountText: '$1.25 Value Deals on Household & Crafts',
    verifiedScore: 96,
    loyaltyProgramName: 'Dollar Tree Value Seekers',
    loyaltyProgramPerk: 'Early notice on seasonal truckloads and craft supply drops',
    hasWeeklyAd: true,
    weeklyAdCount: 20,
    digitalCouponsCount: 0,
    rewardsCount: 0,
    inStoreLocationsCount: 8000
  },
  {
    id: 'store-familydollar',
    name: 'Family Dollar',
    slug: 'family-dollar',
    domain: 'familydollar.com',
    logo: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Household & Cleaning',
    retailerCategory: 'GENERAL RETAIL',
    description: 'Neighborhood discount store featuring Smart Coupons, weekly circulars, and affordable family supplies.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 20,
    dealCount: 85,
    popularDiscountText: 'Smart Coupons: $5 off $25 & BOGO 50% Apparel',
    verifiedScore: 96,
    loyaltyProgramName: 'Smart Coupons',
    loyaltyProgramPerk: 'In-app digital coupon wallet clipped directly to phone number',
    hasWeeklyAd: true,
    weeklyAdCount: 30,
    digitalCouponsCount: 60,
    rewardsCount: 5,
    inStoreLocationsCount: 8200
  },

  // 4. HOME IMPROVEMENT
  {
    id: 'store-homedepot',
    name: 'The Home Depot',
    slug: 'home-depot',
    domain: 'homedepot.com',
    logo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Home & Garden',
    retailerCategory: 'HOME IMPROVEMENT',
    description: 'World’s largest home improvement specialty retailer with tools, lumber, appliances, lawn & garden, and ProXtra rewards.',
    cashbackRate: 2.0,
    allowsStacking: false,
    couponCount: 25,
    dealCount: 190,
    popularDiscountText: 'Special Buy of the Day + Milwaukee/DeWalt Tool Bundles',
    verifiedScore: 98,
    loyaltyProgramName: 'Home Depot ProXtra & Perks',
    loyaltyProgramPerk: 'Personalized volume pricing and tool rental credits',
    hasWeeklyAd: true,
    weeklyAdCount: 45,
    digitalCouponsCount: 20,
    rewardsCount: 8,
    inStoreLocationsCount: 2300
  },
  {
    id: 'store-lowes',
    name: "Lowe's",
    slug: 'lowes',
    domain: 'lowes.com',
    logo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Home & Garden',
    retailerCategory: 'HOME IMPROVEMENT',
    description: 'Major home improvement retailer offering MyLowe’s Rewards, daily flash deals, Craftsman/Kobalt tools, and major appliances.',
    cashbackRate: 2.5,
    allowsStacking: true,
    couponCount: 22,
    dealCount: 175,
    popularDiscountText: 'MyLowe’s Rewards: Earn Points + 5% with Lowe’s Card',
    verifiedScore: 97,
    loyaltyProgramName: "MyLowe's Rewards",
    loyaltyProgramPerk: 'Earn points towards MyLowe’s Money on every DIY purchase',
    hasWeeklyAd: true,
    weeklyAdCount: 40,
    digitalCouponsCount: 30,
    rewardsCount: 10,
    inStoreLocationsCount: 1730
  },
  {
    id: 'store-menards',
    name: 'Menards',
    slug: 'menards',
    domain: 'menards.com',
    logo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Home & Garden',
    retailerCategory: 'HOME IMPROVEMENT',
    description: 'Midwest home improvement leader famous for the legendary 11% Mail-In Rebate on virtually everything in the store.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 12,
    dealCount: 95,
    popularDiscountText: '11% OFF Everything Mail-In Rebate Sale',
    verifiedScore: 99,
    loyaltyProgramName: 'Menards 11% Rebate Program',
    loyaltyProgramPerk: 'Receive 11% back in store merchandise credit certificates on all purchases',
    hasWeeklyAd: true,
    weeklyAdCount: 35,
    digitalCouponsCount: 10,
    rewardsCount: 4,
    inStoreLocationsCount: 335
  },
  {
    id: 'store-harborfreight',
    name: 'Harbor Freight Tools',
    slug: 'harbor-freight',
    domain: 'harborfreight.com',
    logo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Home & Garden',
    retailerCategory: 'HOME IMPROVEMENT',
    description: 'High-value hand tools, generators, power tools, and automotive diagnostic gear with Inside Track Club savings.',
    cashbackRate: 2.0,
    allowsStacking: false,
    couponCount: 30,
    dealCount: 130,
    popularDiscountText: '20% OFF Single Item Coupon + Free Gift with Purchase',
    verifiedScore: 98,
    loyaltyProgramName: 'Inside Track Club',
    loyaltyProgramPerk: 'Exclusive member pricing on 200+ top tools every month',
    hasWeeklyAd: true,
    weeklyAdCount: 30,
    digitalCouponsCount: 45,
    rewardsCount: 6,
    inStoreLocationsCount: 1400
  },
  {
    id: 'store-tractorsupply',
    name: 'Tractor Supply Co.',
    slug: 'tractor-supply',
    domain: 'tractorsupply.com',
    logo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Home & Garden',
    retailerCategory: 'HOME IMPROVEMENT',
    description: 'For Life Out Here: Farm supplies, pet food, workwear, lawn tractors, fencing, and Neighbor’s Club rewards.',
    cashbackRate: 2.0,
    allowsStacking: true,
    couponCount: 16,
    dealCount: 88,
    popularDiscountText: 'Neighbor’s Club Rewards: Earn Points on Feed, Tools & Workwear',
    verifiedScore: 97,
    loyaltyProgramName: "Neighbor's Club",
    loyaltyProgramPerk: 'Earn rewards, free trailer rental days, and seasonal coupons',
    hasWeeklyAd: true,
    weeklyAdCount: 25,
    digitalCouponsCount: 20,
    rewardsCount: 8,
    inStoreLocationsCount: 2200
  },

  // 5. AUTOMOTIVE
  {
    id: 'store-autozone',
    name: 'AutoZone',
    slug: 'autozone',
    domain: 'autozone.com',
    logo: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Automotive & Hardware',
    retailerCategory: 'AUTOMOTIVE',
    description: 'Leading distributor of automotive replacement parts, Duralast batteries, Mobil 1 oil change bundles, and free battery testing.',
    cashbackRate: 3.0,
    allowsStacking: false,
    couponCount: 20,
    dealCount: 105,
    popularDiscountText: '$36.99 Mobil 1 Oil + Filter Bundle + $20 AutoZone Reward',
    verifiedScore: 98,
    loyaltyProgramName: 'AutoZone Rewards',
    loyaltyProgramPerk: 'Make 5 purchases of $20+ and receive a $20 reward certificate',
    hasWeeklyAd: true,
    weeklyAdCount: 25,
    digitalCouponsCount: 15,
    rewardsCount: 6,
    inStoreLocationsCount: 6300
  },
  {
    id: 'store-oreilly',
    name: "O'Reilly Auto Parts",
    slug: 'oreilly-auto-parts',
    domain: 'oreillyauto.com',
    logo: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Automotive & Hardware',
    retailerCategory: 'AUTOMOTIVE',
    description: 'Better Parts, Better Prices: DIY auto care, brake pad deals, free loaner tools, and O’Rewards points.',
    cashbackRate: 2.5,
    allowsStacking: true,
    couponCount: 18,
    dealCount: 95,
    popularDiscountText: "O'Rewards: $5 Reward for Every 150 Points + Castrol Oil Sale",
    verifiedScore: 97,
    loyaltyProgramName: "O'Rewards",
    loyaltyProgramPerk: 'Earn 1 point per $1 spent. 150 points = $5 reward',
    hasWeeklyAd: true,
    weeklyAdCount: 22,
    digitalCouponsCount: 18,
    rewardsCount: 5,
    inStoreLocationsCount: 6000
  },
  {
    id: 'store-advanceauto',
    name: 'Advance Auto Parts',
    slug: 'advance-auto-parts',
    domain: 'advanceautoparts.com',
    logo: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Automotive & Hardware',
    retailerCategory: 'AUTOMOTIVE',
    description: 'Auto parts, wiper blades, DieHard batteries, and Speed Perks loyalty discounts for DIYers.',
    cashbackRate: 3.5,
    allowsStacking: true,
    couponCount: 22,
    dealCount: 110,
    popularDiscountText: '15-20% Off Online Code + DieHard Battery Rebates',
    verifiedScore: 98,
    loyaltyProgramName: 'Speed Perks',
    loyaltyProgramPerk: '$5 Perk bucks on qualifying spend + free curbside pickup in 30 mins',
    hasWeeklyAd: true,
    weeklyAdCount: 20,
    digitalCouponsCount: 25,
    rewardsCount: 7,
    inStoreLocationsCount: 4700
  },

  // 6. ELECTRONICS
  {
    id: 'store-bestbuy',
    name: 'Best Buy',
    slug: 'best-buy',
    domain: 'bestbuy.com',
    logo: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Electronics & Computers',
    retailerCategory: 'ELECTRONICS',
    description: 'Top consumer electronics retailer with Deal of the Day, price matching, Apple, 4K TVs, and My Best Buy perks.',
    cashbackRate: 1.0,
    allowsStacking: false,
    couponCount: 28,
    dealCount: 210,
    popularDiscountText: 'Deal of the Day + Up to $300 Off Laptops and 4K Smart TVs',
    verifiedScore: 99,
    loyaltyProgramName: 'My Best Buy',
    loyaltyProgramPerk: 'Free shipping with no minimum + exclusive member pricing drops',
    hasWeeklyAd: true,
    weeklyAdCount: 48,
    digitalCouponsCount: 25,
    rewardsCount: 10,
    inStoreLocationsCount: 950
  },

  // 7. OFFICE / SCHOOL
  {
    id: 'store-staples',
    name: 'Staples',
    slug: 'staples',
    domain: 'staples.com',
    logo: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Office & School',
    retailerCategory: 'OFFICE / SCHOOL',
    description: 'Work and school headquarters with copy & print savings, office chairs, copy paper rebates, and Staples Rewards.',
    cashbackRate: 3.0,
    allowsStacking: true,
    couponCount: 24,
    dealCount: 130,
    popularDiscountText: '$5 Off $25 Copy Paper + Free In-Store Recycling Rewards',
    verifiedScore: 98,
    loyaltyProgramName: 'Staples Easy Rewards',
    loyaltyProgramPerk: 'Earn points on purchases, ink recycling, and printing services',
    hasWeeklyAd: true,
    weeklyAdCount: 30,
    digitalCouponsCount: 35,
    rewardsCount: 12,
    inStoreLocationsCount: 1000
  },
  {
    id: 'store-officedepot',
    name: 'Office Depot / OfficeMax',
    slug: 'office-depot',
    domain: 'officedepot.com',
    logo: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Office & School',
    retailerCategory: 'OFFICE / SCHOOL',
    description: 'Office furniture, tech, school supplies, and 100% back in bonus rewards on qualifying supplies.',
    cashbackRate: 3.5,
    allowsStacking: true,
    couponCount: 20,
    dealCount: 115,
    popularDiscountText: '20% Off Regular Priced Item + 100% Back in Bonus Rewards',
    verifiedScore: 97,
    loyaltyProgramName: 'Office Depot Rewards',
    loyaltyProgramPerk: '2% back in rewards on supplies + $2 back per recycled ink cartridge',
    hasWeeklyAd: true,
    weeklyAdCount: 25,
    digitalCouponsCount: 28,
    rewardsCount: 8,
    inStoreLocationsCount: 950
  },

  // 8. CLOTHING & APPAREL
  {
    id: 'store-oldnavy',
    name: 'Old Navy',
    slug: 'old-navy',
    domain: 'oldnavy.gap.com',
    logo: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Clothing & Fashion',
    retailerCategory: 'CLOTHING',
    description: 'Everyday budget-friendly fashion for the entire family with 50% Off Steals and Super Cash savings.',
    cashbackRate: 4.0,
    allowsStacking: true,
    couponCount: 30,
    dealCount: 160,
    popularDiscountText: '50% Off Everything Online Event + Earn Super Cash',
    verifiedScore: 98,
    loyaltyProgramName: 'Navyist Rewards',
    loyaltyProgramPerk: 'Earn points at Old Navy, Gap, Banana Republic & Athleta + Super Cash redemption',
    hasWeeklyAd: true,
    weeklyAdCount: 35,
    digitalCouponsCount: 40,
    rewardsCount: 10,
    inStoreLocationsCount: 1200
  },
  {
    id: 'store-kohls',
    name: "Kohl's",
    slug: 'kohls',
    domain: 'kohls.com',
    logo: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Clothing & Fashion',
    retailerCategory: 'CLOTHING',
    description: 'Department store savings champion with Kohl’s Cash ($10 for every $50 spent), 15-30% Mystery Codes, and Sephora.',
    cashbackRate: 3.0,
    allowsStacking: true,
    couponCount: 35,
    dealCount: 220,
    popularDiscountText: 'Take 15-20% Off + Earn $10 Kohl’s Cash for Every $50',
    verifiedScore: 99,
    loyaltyProgramName: "Kohl's Rewards",
    loyaltyProgramPerk: 'Earn 5% rewards on every purchase + $10 Kohl’s Cash events',
    hasWeeklyAd: true,
    weeklyAdCount: 45,
    digitalCouponsCount: 50,
    rewardsCount: 18,
    inStoreLocationsCount: 1165
  },
  {
    id: 'store-tjmaxx',
    name: 'TJ Maxx / Marshalls',
    slug: 'tj-maxx',
    domain: 'tjmaxx.tjx.com',
    logo: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Clothing & Fashion',
    retailerCategory: 'CLOTHING',
    description: 'Off-price department treasure hunt with genuine brand-name clothing, shoes, and home goods 20-60% below retail.',
    cashbackRate: 1.5,
    allowsStacking: false,
    couponCount: 12,
    dealCount: 105,
    popularDiscountText: 'Designer Clearance Markdowns 50-70% Below Department Stores',
    verifiedScore: 97,
    loyaltyProgramName: 'TJX Rewards',
    loyaltyProgramPerk: 'Earn $10 reward certificates across TJ Maxx, Marshalls, HomeGoods & Sierra',
    hasWeeklyAd: false,
    weeklyAdCount: 0,
    digitalCouponsCount: 0,
    rewardsCount: 4,
    inStoreLocationsCount: 3500
  },

  // 9. BEAUTY
  {
    id: 'store-ulta',
    name: 'Ulta Beauty',
    slug: 'ulta',
    domain: 'ulta.com',
    logo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Beauty & Skincare',
    retailerCategory: 'BEAUTY',
    description: 'All Things Beauty, All in One Place: Drugstore to prestige cosmetics, 21 Days of Beauty, and $3.50 off $15 coupons.',
    cashbackRate: 4.0,
    allowsStacking: true,
    couponCount: 25,
    dealCount: 155,
    popularDiscountText: '$3.50 OFF $15 Coupon + 50% Off 21 Days of Beauty Steals',
    verifiedScore: 99,
    loyaltyProgramName: 'Ulta Beauty Rewards',
    loyaltyProgramPerk: 'Points convert directly to dollar discounts on any product or salon service',
    hasWeeklyAd: true,
    weeklyAdCount: 40,
    digitalCouponsCount: 30,
    rewardsCount: 15,
    inStoreLocationsCount: 1350
  },
  {
    id: 'store-bathandbodyworks',
    name: 'Bath & Body Works',
    slug: 'bath-and-body-works',
    domain: 'bathandbodyworks.com',
    logo: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Beauty & Skincare',
    retailerCategory: 'BEAUTY',
    description: 'World-famous 3-wick candles, Wallflowers fragrance refills, body mist, and $3.95 Hand Soap promotions.',
    cashbackRate: 2.0,
    allowsStacking: true,
    couponCount: 18,
    dealCount: 90,
    popularDiscountText: 'Buy 3 Get 3 FREE Body Care + 20% Off Mailer Coupon Stack',
    verifiedScore: 98,
    loyaltyProgramName: 'My Bath & Body Works Rewards',
    loyaltyProgramPerk: 'Free full-size product (up to $16.95 value) with every 100 points earned',
    hasWeeklyAd: true,
    weeklyAdCount: 20,
    digitalCouponsCount: 25,
    rewardsCount: 8,
    inStoreLocationsCount: 1800
  },

  // 10. RESTAURANTS / FOOD
  {
    id: 'store-dominos',
    name: "Domino's Pizza",
    slug: 'dominos',
    domain: 'dominos.com',
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'RESTAURANTS / FOOD',
    description: 'Carryout and delivery pizza leader with national $7.99 Mix & Match Deal and Domino’s Rewards.',
    cashbackRate: 1.0,
    allowsStacking: false,
    couponCount: 15,
    dealCount: 55,
    popularDiscountText: '$7.99 Mix & Match Deal (2 or more items: Medium 2-Topping, Bread, Pasta)',
    verifiedScore: 99,
    loyaltyProgramName: "Domino's Rewards",
    loyaltyProgramPerk: 'Earn 10 points per order. 60 points = Free medium 2-topping pizza',
    hasWeeklyAd: false,
    weeklyAdCount: 0,
    digitalCouponsCount: 20,
    rewardsCount: 6,
    inStoreLocationsCount: 6700
  },
  {
    id: 'store-mcdonalds',
    name: "McDonald's",
    slug: 'mcdonalds',
    domain: 'mcdonalds.com',
    logo: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'RESTAURANTS / FOOD',
    description: 'Global fast food favorite featuring the $5 Meal Deal, Free Fry Friday in-app coupon, and MyMcDonald’s Rewards.',
    cashbackRate: 0,
    allowsStacking: false,
    couponCount: 12,
    dealCount: 45,
    popularDiscountText: '$5 Meal Deal + Free Medium Fries Every Friday in App',
    verifiedScore: 99,
    loyaltyProgramName: "MyMcDonald's Rewards",
    loyaltyProgramPerk: '100 points per $1 spent unlock free burgers, breakfast, and drinks',
    hasWeeklyAd: false,
    weeklyAdCount: 0,
    digitalCouponsCount: 18,
    rewardsCount: 8,
    inStoreLocationsCount: 13500
  },

  // 11. PET
  {
    id: 'store-chewy',
    name: 'Chewy',
    slug: 'chewy',
    domain: 'chewy.com',
    logo: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Pet Supplies',
    retailerCategory: 'PET',
    description: 'Online pet destination with 35% off your first Autoship order, free 1-3 day shipping over $49, and pharmacy care.',
    cashbackRate: 4.0,
    allowsStacking: true,
    couponCount: 25,
    dealCount: 140,
    popularDiscountText: '35% Off First Autoship Order + Spend $100 Get $30 eGift Card',
    verifiedScore: 99,
    loyaltyProgramName: 'Chewy Autoship Savings',
    loyaltyProgramPerk: 'Automatic 5% off recurring food and litter deliveries with flexible cancellation',
    hasWeeklyAd: true,
    weeklyAdCount: 30,
    digitalCouponsCount: 40,
    rewardsCount: 5,
    inStoreLocationsCount: 0
  },
  {
    id: 'store-petsmart',
    name: 'PetSmart',
    slug: 'petsmart',
    domain: 'petsmart.com',
    logo: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Pet Supplies',
    retailerCategory: 'PET',
    description: 'Full-service pet store offering Treats Rewards, veterinary clinics, grooming discounts, and BOGO pet food sales.',
    cashbackRate: 3.0,
    allowsStacking: true,
    couponCount: 20,
    dealCount: 110,
    popularDiscountText: 'Treats Rewards: Buy 1 Get 1 50% Off Dog & Cat Treats + 20% Off Pickup',
    verifiedScore: 98,
    loyaltyProgramName: 'PetSmart Treats Rewards',
    loyaltyProgramPerk: 'Earn 8 points per dollar + free surprise on pet’s birthday',
    hasWeeklyAd: true,
    weeklyAdCount: 25,
    digitalCouponsCount: 30,
    rewardsCount: 8,
    inStoreLocationsCount: 1650
  },

  // 12. GAS / CONVENIENCE
  {
    id: 'store-shell',
    name: 'Shell Fuel & Convenience',
    slug: 'shell',
    domain: 'shell.us',
    logo: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Automotive & Hardware',
    retailerCategory: 'GAS / CONVENIENCE',
    description: 'Fuel Rewards program saving $0.05 to $0.25+ per gallon on Shell V-Power NiTRO+ and regular gasoline.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 10,
    dealCount: 40,
    popularDiscountText: 'Save $0.05 to $0.25/gal with Fuel Rewards + Dunkin’ Fuel Bonus',
    verifiedScore: 99,
    loyaltyProgramName: 'Shell Fuel Rewards',
    loyaltyProgramPerk: 'Guaranteed 5¢/gal savings with Gold Status + link Dunkin / AAA for extra cents off',
    hasWeeklyAd: false,
    weeklyAdCount: 0,
    digitalCouponsCount: 12,
    rewardsCount: 4,
    inStoreLocationsCount: 12500
  },
  {
    id: 'store-caseys',
    name: "Casey's General Stores",
    slug: 'caseys',
    domain: 'caseys.com',
    logo: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GAS / CONVENIENCE',
    description: 'Famous handmade pizza, fuel discounts, and Casey’s Rewards saving cents per gallon or donating to local schools.',
    cashbackRate: 1.5,
    allowsStacking: true,
    couponCount: 15,
    dealCount: 50,
    popularDiscountText: 'Buy Any Large Pizza Get One 50% Off + $0.10/gal Fuel Reward',
    verifiedScore: 98,
    loyaltyProgramName: "Casey's Rewards",
    loyaltyProgramPerk: 'Earn 10 points per $1 in-store and 5 points per gallon at pump',
    hasWeeklyAd: true,
    weeklyAdCount: 15,
    digitalCouponsCount: 20,
    rewardsCount: 6,
    inStoreLocationsCount: 2600
  },
  {
    id: 'store-circlek',
    name: 'Circle K',
    slug: 'circle-k',
    domain: 'circlek.com',
    logo: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'Groceries & Food',
    retailerCategory: 'GAS / CONVENIENCE',
    description: 'Neighborhood convenience stores with Sip & Save beverage club, gas discounts, and Inner Circle member deals.',
    cashbackRate: 1.0,
    allowsStacking: true,
    couponCount: 12,
    dealCount: 45,
    popularDiscountText: 'Inner Circle: Save $0.25/gal on First 5 Fill-ups + $0.89 Polar Pop',
    verifiedScore: 97,
    loyaltyProgramName: 'Circle K Inner Circle',
    loyaltyProgramPerk: 'Earn food & drink rewards + 5¢ off every gallon of fuel everyday',
    hasWeeklyAd: true,
    weeklyAdCount: 10,
    digitalCouponsCount: 15,
    rewardsCount: 5,
    inStoreLocationsCount: 7000
  }
];

// Sample Location Database for Store-First & Local ZIP Filtering
export const sampleStoreLocations: StoreLocation[] = [
  // CVS Locations
  {
    id: 'loc-cvs-1',
    storeId: 'store-cvs',
    storeName: 'CVS Pharmacy',
    storeNumber: 'Store #2841',
    address: '1420 W 86th St',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46260',
    distanceMiles: 1.2,
    hasPharmacy: true,
    hasGrocery: true
  },
  {
    id: 'loc-cvs-2',
    storeId: 'store-cvs',
    storeName: 'CVS Pharmacy',
    storeNumber: 'Store #1042',
    address: '500 E 4th St',
    city: 'Des Moines',
    state: 'IA',
    zipCode: '50309',
    distanceMiles: 2.5,
    hasPharmacy: true,
    hasGrocery: true
  },
  {
    id: 'loc-cvs-3',
    storeId: 'store-cvs',
    storeName: 'CVS Pharmacy',
    storeNumber: 'Store #8391',
    address: '1900 Broadway',
    city: 'New York',
    state: 'NY',
    zipCode: '10023',
    distanceMiles: 0.8,
    hasPharmacy: true,
    hasGrocery: true
  },
  // Kroger Locations
  {
    id: 'loc-kroger-1',
    storeId: 'store-kroger',
    storeName: 'Kroger',
    storeNumber: 'Store #412',
    address: '2550 E 86th St',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46240',
    distanceMiles: 3.1,
    hasPharmacy: true,
    hasGrocery: true,
    hasGas: true
  },
  // Walmart Locations
  {
    id: 'loc-walmart-1',
    storeId: 'store-walmart',
    storeName: 'Walmart Supercenter',
    storeNumber: 'Store #1509',
    address: '7245 US 31 S',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46227',
    distanceMiles: 4.8,
    hasPharmacy: true,
    hasGrocery: true,
    hasGas: true
  },
  // Home Depot Locations
  {
    id: 'loc-hd-1',
    storeId: 'store-homedepot',
    storeName: 'The Home Depot',
    storeNumber: 'Store #2014',
    address: '9855 N Michigan Rd',
    city: 'Carmel',
    state: 'IN',
    zipCode: '46032',
    distanceMiles: 2.9
  },
  // AutoZone Locations
  {
    id: 'loc-autozone-1',
    storeId: 'store-autozone',
    storeName: 'AutoZone',
    storeNumber: 'Store #3188',
    address: '6140 N Keystone Ave',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46220',
    distanceMiles: 2.1
  }
];

export const sampleLoyaltyPrograms: StoreLoyaltyProgram[] = [
  {
    id: 'prog-cvs',
    storeId: 'store-cvs',
    storeName: 'CVS Pharmacy',
    programName: 'CVS ExtraCare',
    isFree: true,
    perksDescription: '2% back in ExtraBucks + clip weekly digital manufacturer coupons for instant register savings.',
    digitalClipAvailable: true,
    userEnrolled: true
  },
  {
    id: 'prog-kroger',
    storeId: 'store-kroger',
    storeName: 'Kroger',
    programName: 'Kroger Plus Card',
    isFree: true,
    perksDescription: 'Unlocks sale prices, 5x digital coupon events, and up to $1.00/gal fuel point discounts.',
    digitalClipAvailable: true,
    userEnrolled: true
  },
  {
    id: 'prog-target',
    storeId: 'store-target',
    storeName: 'Target',
    programName: 'Target Circle',
    isFree: true,
    perksDescription: 'Automatic digital deals applied at checkout + special gift card bonus promotions.',
    digitalClipAvailable: true,
    userEnrolled: false
  },
  {
    id: 'prog-walgreens',
    storeId: 'store-walgreens',
    storeName: 'Walgreens',
    programName: 'myWalgreens',
    isFree: true,
    perksDescription: '1% to 5% Walgreens Cash rewards on store items + exclusive in-app circular coupons.',
    digitalClipAvailable: true,
    userEnrolled: true
  },
  {
    id: 'prog-dollargeneral',
    storeId: 'store-dollargeneral',
    storeName: 'Dollar General',
    programName: 'DG Digital Coupons',
    isFree: true,
    perksDescription: '$5 OFF $25 Saturday coupons + digital coupon clipping entered at pin pad.',
    digitalClipAvailable: true,
    userEnrolled: false
  }
];
